import { Link } from 'react-router-dom'
import { BerryMark, CodeBlock, PixelGame, SectionHead } from '../components'
import { consoleExamples, gameProjects } from '../data'
import { LiveGame } from '../studio'

export default function Home() {
  return <>
    <section className="hero shell">
      <div className="hero-copy reveal"><p className="eyebrow"><span>PB</span> A scripting language for small games</p><h1>Make little games.<br /><em>Have a lot of fun.</em></h1><p className="hero-intro">Pogberry combines a readable dynamically typed language with graphics, input, modules, collections, classes, and a small C bytecode VM.</p><div className="hero-actions"><Link className="button primary" to="/playground">Open the browser editor <span>→</span></Link><Link className="text-link" to="/learn">Read the documentation</Link></div><div className="proof-strip"><span><i className="status-dot" /> C bytecode VM</span><span>WebAssembly build</span><span>Raylib host</span></div></div>
        <div className="hero-art reveal"><div className="sun-doodle" /><span className="hand-note note-one">Pogberry source</span><div className="hero-code-card"><CodeBlock code={`use "engine.graphics";\n\nlet x = 36;\n\nfun update(dt) {\n  x = x + 80 * dt;\n}\n\nfun draw() {\n  graphics.clear(31, 28, 40);\n  graphics.rectangle(x, 120, 24, 24,\n    232, 79, 115);\n}`} title="main.pb" compact /></div><span className="hand-note note-two">the rendered frame</span><PixelGame /></div>
    </section>

    <div className="marquee"><div className="marquee-track"><span>FUNCTIONS</span><i>·</i><span>CLASSES</span><i>·</i><span>CLOSURES</span><i>·</i><span>LISTS + MAPS</span><i>·</i><span>MODULES</span><i>·</i><span>GRAPHICS</span><i>·</i><span>INPUT</span><i>·</i><span>FUNCTIONS</span><i>·</i><span>CLASSES</span><i>·</i><span>CLOSURES</span><i>·</i><span>LISTS + MAPS</span><i>·</i><span>MODULES</span><i>·</i><span>GRAPHICS</span><i>·</i><span>INPUT</span><i>·</i></div></div>

    <section className="section shell"><SectionHead number="01" label="the language" title="Small syntax." italic="Useful features." text="Pogberry is intended to be approachable without limiting projects to a single file or a single programming style." /><div className="feature-grid"><article className="feature-card lavender reveal"><span className="feature-no">LANGUAGE</span><div className="feature-icon braces">{'{ '}<i>♥</i>{' }'}</div><h3>Functions, closures, and classes</h3><p>Write straightforward functions, keep local state in closures, or organize game actors into classes with inheritance.</p><code>let player = Player("Mira");</code></article><article className="feature-card coral reveal"><span className="feature-no">DATA</span><div className="feature-icon bolt">[ ]</div><h3>Lists and ordered maps</h3><p>Mutable collections include checked indexes, negative list indexes, structural equality, and familiar methods.</p><code>inventory.push("potion");</code></article><article className="feature-card mint reveal"><span className="feature-no">PROJECTS</span><div className="feature-icon blocks"><i /><i /><i /></div><h3>Source modules</h3><p>Split a project into folders and files. Modules have isolated globals and explicit exports.</p><code>use "game/player";</code></article></div></section>

    <section className="section playable-home"><div className="shell"><SectionHead inverse number="02" label="playable example" title="A Pogberry game" italic="running in the browser." text="The WebAssembly VM runs update and draw, the browser renders its graphics commands, and keyboard or touch input is sent back to the game." /><div className="playable-home-grid"><LiveGame project={gameProjects.firstGame} /><div className="playable-source"><CodeBlock code={gameProjects.firstGame.files['main.pb']} title="main.pb" compact /><Link className="button primary" to="/examples">More running examples →</Link></div></div></div></section>

    <section className="section shell home-language"><SectionHead number="03" label="ordinary programs" title="The game tools sit on" italic="a complete core language." text="The same interpreter can run a terminal script, a multi-file application, an embedded behavior module, or a graphical game." /><div className="language-showcase reveal"><div className="language-copy"><span>CORE LANGUAGE</span><h3>Readable state and behavior</h3><ul><li><b>Lexical scope.</b> Locals live inside the block where they are declared.</li><li><b>First-class functions.</b> Functions may be stored, passed, returned, and closed over.</li><li><b>Checked operations.</b> Invalid indexes, arguments, and arithmetic produce diagnostics.</li><li><b>Module boundaries.</b> A file exports only the declarations other files should use.</li></ul><Link className="button primary" to="/learn">Learn the language →</Link></div><CodeBlock code={consoleExamples.classes} title="actors.pb" /></div></section>

    <section className="section game-kit"><div className="shell"><div className="kit-intro reveal"><p className="eyebrow"><span>04</span> game modules</p><h2>The parts a 2D game needs</h2><p>Graphics and keyboard input are available in the browser editor now. Audio, physics, packaged assets, and save storage remain under development and are deliberately left undocumented until their APIs settle.</p><Link className="text-link" to="/learn#games">Read the game guide →</Link></div><div className="kit-map reveal"><div className="kit-core"><BerryMark big /><strong>YOUR<br />GAME</strong></div><div className="orbit orbit-1" /><div className="orbit orbit-2" /><article className="kit-item graphics"><i>▧</i><div><strong>graphics</strong><span>rectangles · circles · text</span></div><small className="available">documented</small></article><article className="kit-item input"><i>⌁</i><div><strong>input</strong><span>keyboard actions</span></div><small className="available">documented</small></article><article className="kit-item audio"><i>♫</i><div><strong>audio</strong><span>sounds · music</span></div><small>TBA</small></article><article className="kit-item physics"><i>◉</i><div><strong>physics</strong><span>bodies · collisions</span></div><small>TBA</small></article><article className="kit-item files"><i>⌑</i><div><strong>assets + saves</strong><span>portable game data</span></div><small>TBA</small></article><article className="kit-item hosts"><i>↝</i><div><strong>hosts</strong><span>Raylib · web · custom</span></div><small>in development</small></article></div></div></section>

    <section className="section shell home-examples"><SectionHead number="05" label="example projects" title="Four small games," italic="source included." text="Run each project and see how its input, update logic, state, collections, modules, and drawing code fit together." /><div className="project-strip reveal"><article className="project-card snake"><span>LISTS + INPUT</span><div className="mini-game snake-grid"><i /><i /><i /><i /><b /></div><h3>Pocket snake</h3><p>A playable grid game stored as a list of positions.</p></article><article className="project-card mole"><span>DELTA TIME</span><div className="mini-game mole-grid"><i /><i /><i /></div><h3>Bouncing ball</h3><p>Velocity, frame-rate independent movement, and collision.</p></article><article className="project-card adventure"><span>RULES + SCORE</span><div className="mini-game book-grid">pb</div><h3>Berry catcher</h3><p>Player input, falling objects, collision, and score state.</p></article></div><div className="center-action"><Link className="button primary" to="/examples">Run the examples →</Link></div></section>
  </>
}
